FROM resin/raspberrypi3-golang:1.10-slim

WORKDIR /go/src/github.com/rjsheperd/oodie
COPY vendor /go/src/

COPY main.go .

RUN CGO_ENABLED=0 GOARCH=arm GOOS=linux \
  go build -a -installsuffix cgo -o oodie .

WORKDIR /app

RUN cp /go/src/github.com/rjsheperd/oodie/oodie .
COPY start.sh .

# Enable systemd init system in container
# ENV INITSYSTEM on

# Run the start script
CMD ["sh", "/app/start.sh"]
